version: '2'
services:
  store:
    image: redis
    ports:
      - "1234:1234"
  db:
    image: mongo
    ports:
      - "123:123"  
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - "db"
      - "store"
    environment:
      - MONGO_HOST=db
      - REDIS_HOST=store
 



