version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - "db"
      - "redis"
    environment:
      - MONGODB_HOST=db
      - REDIS_HOST=redis

