version: '2'
services:
  store:
    image: mysql
    ports:
      - "123:123"
  db:
    image: mongo
    ports:
      - "123:123"  
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      - MONGO_HOST=db
 



