version: '2'
services:
  redis:
    image: redis
    ports:
      - "2345:2345"  
  db:
    image: mongo
    ports:
      - "123:123"  
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - "redis"
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=db

